CREATE DATABASE nemdb;

CREATE USER nemuser WITH PASSWORD 'nempassword';

GRANT ALL PRIVILEGES ON DATABASE nemdb TO nemuser;

\connect nemdb
GRANT ALL ON SCHEMA public TO nemuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nemuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nemuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO nemuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO nemuser;